permissionInformation={
  {
    icon=R.drawable.ic_file_outline,
    title="存储";
    summary="用于存储项目、编辑项目、调试项目等";
    permissions={"android.permission.WRITE_EXTERNAL_STORAGE","android.permission.READ_EXTERNAL_STORAGE"};
  },
  {
    icon=R.drawable.ic_phone_outline,
    title="电话";
    summary="用于统计软件、调试项目";
    permissions={"android.permission.READ_PHONE_STATE"};
  },
  {
    icon=R.drawable.ic_map_marker_outline,
    title="位置信息";
    summary="用于调试项目";
    permissions={"android.permission.ACCESS_COARSE_LOCATION","android.permission.ACCESS_FINE_LOCATION"};
  },
  {
    icon=R.drawable.ic_camera_outline,
    title="相机";
    summary="用于调试项目";
    permissions={"android.permission.CAMERA"};
  },
  {
    icon=R.drawable.ic_microphone_outline,
    title="麦克风";
    summary="用于调试项目";
    permissions={"android.permission.RECORD_AUDIO"};
  },
  {
    icon=R.drawable.ic_account_multiple_outline,
    title="通讯录";
    summary="用于调试项目";
    permissions={"android.permission.WRITE_CONTACTS"};
  },
  {
    icon=R.drawable.ic_message_text_outline,
    title="短信";
    summary="用于调试项目";
    permissions={"android.permission.SEND_SMS"};
  },
  {
    icon=R.drawable.ic_phone_log_outline,
    title="通话记录";
    summary="用于调试项目";
    permissions={"android.permission.WRITE_CALL_LOG"};
  },
  {
    icon=R.drawable.ic_calendar_month_outline,
    title="日历";
    summary="用于调试项目";
    permissions={"android.permission.WRITE_CALENDAR"};
  },
}
welcomeMessage="我是一款依赖 Aide 的编辑器"
