return {
  LinearLayout;
  layout_width="fill";
  orientation="vertical";
  layoutTransition=newLayoutTransition();
  contentDescription="配置版本";
  {--配置版本
    LinearLayoutCompat;
    layout_width="fill";
    orientation="vertical";
    layout_height="40dp";
    gravity="bottom";
    focusable=false;
    layout_marginLeft="16dp";
    layout_marginRight="16dp";
    {
      AppCompatTextView;
      text="* 配置版本";
      textSize="14sp";
      --typeface=Typeface.defaultFromStyle(Typeface.BOLD);
      textColor=theme.color.colorPrimary;
      layout_marginBottom="8dp";
    };
  };
  {
    ChipGroup;
    id="configVersionsGroup";
    layout_width="fill";
    layoutTransition=newLayoutTransition();
    layout_marginLeft="16dp";
    layout_marginRight="16dp";
    layout_marginBottom="8dp";
    singleSelection=true;
    chipSpacing="4dp";
  };
}