androluaVersions={
  {"5.0.10(1.6)(armeabi-v7a)",1699},
  {"5.0.16(1.2)(arm64-v8a)",1299},
  {"5.0.18(1.1)(armeabi-v7a,arm64-v8a)",1199}
}--所有androlua版本号
appVersions={"2.1"}--所有app版本号
format={
  "settings.gradle",
  "gradle.properties",
  ".aidelua/config.lua",
  "app/.aidelua/config.lua",
  "app/build.gradle",
  "app/src/main/AndroidManifest.xml",
  "app/src/main/res/values/strings.xml",
  "app/src/main/assets_bin/init.lua",
  "app/src/main/assets_bin/main.lua",
  "androlua/build.gradle",
}
