appname="底线"--插件名
packagename="com.aidelua.bottomline"--插件包名
appver="1.0"
appcode=1099
description="字面意思"
mode="plugin"--模式：插件
utilversion="3.1"--Util版本，此变量不起作用
smallicon=true--当icon.png为小图标时，启用此项
supported2={--支持的APP
  aidelua={mincode=50499,targetcode=59999}
}
thirdplugins={}