appname="插件模板"--插件名
packagename="com.aidelua.plugin"--插件包名
appver="3.1"
appcode=3199
mode="plugin"--模式：插件
supported2={
  --aidelua的3.1版本是从50399版本开始的
  aidelua={mincode=50399,targetcode=59999}
}
thirdplugins={}
events={
  onCreate=function(activityName,savedInstanceState)
    print("进入",activityName,"页面")
    print(appname,"全局代码加载成功")
  end,
}