androluaVersions={"1.5(5.0.10)","1.0(5.0.16)"}--所有androlua版本号
appVersions={"2.1"}--所有app版本号
format={
  "settings.gradle",
  "gradle.properties",
  ".aidelua/config.lua",
  "app/.aidelua/config.lua",
  "app/build.gradle",
  "app/src/main/AndroidManifest.xml",
  "app/src/main/res/values/strings.xml",
  "app/src/main/assets_bin/init.lua",
}
